# Generated by Django 5.2.8 on 2026-07-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0003_doctor_date_naissance_doctor_horaire_doctor_salaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='jours_travail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
