# Generated by Django 5.2.8 on 2026-07-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0004_doctor_jours_travail'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='service_assigne',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
