# Generated by Django 5.2.8 on 2026-07-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0005_patient_service_assigne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lit',
            name='code',
        ),
        migrations.AddField(
            model_name='lit',
            name='numero',
            field=models.CharField(default='001', max_length=10),
        ),
        migrations.AddField(
            model_name='lit',
            name='service',
            field=models.CharField(default='Non défini', max_length=100),
        ),
    ]
