# Generated by Django 5.2.8 on 2026-07-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0006_remove_lit_code_lit_numero_lit_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lit',
            name='chambre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='clinical.chambre'),
        ),
    ]
