# Generated by Django 5.2.8 on 2026-07-12 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical', '0008_medicament_ordonnance'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite_mesure', models.CharField(blank=True, max_length=20)),
                ('valeur_reference_min', models.FloatField(blank=True, null=True)),
                ('valeur_reference_max', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExamenLabo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescription', models.DateTimeField(auto_now_add=True)),
                ('date_resultat', models.DateTimeField(blank=True, null=True)),
                ('resultat_valeur', models.FloatField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('EN_COURS', 'En cours'), ('TERMINE', 'Terminé'), ('VALIDE', 'Validé par le biologiste')], default='EN_ATTENTE', max_length=20)),
                ('medecin_prescripteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.patient')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical.typetest')),
            ],
        ),
    ]
